version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.33.3
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always
    networks:
      - promnet
  exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always
    networks:
      - promnet
  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command: "--config.file=/etc/alertmanager/config.yaml"
    ports:
      - 9093:9093
    restart: always
    networks:
      - promnet
  httpserver:
    build: ./httpserver
    volumes:
        - ./httpserver:/app
    ports:
        - 8000:8000
        - 8001:8001
    command: python3 /app/app.py
    networks:
      - promnet
networks:
  promnet:
    driver: bridge
