global:
  scrape_interval: 10s
  evaluation_interval: 10s # alertの評価間隔
rule_files:
  - rules.yaml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: node
    static_configs:
      - targets:
        - exporter:9100
  - job_name: example
    static_configs:
      - targets:
        - httpserver:8000
  - job_name: blackbox
    scrape_interval: 10s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - '192.168.3.1'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
