global:
  scrape_interval: 10s
  evaluation_interval: 10s # alertの評価間隔
rule_files:
  - rules.yaml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: node
    static_configs:
      - targets:
        - exporter:9100
  - job_name: example
    static_configs:
      - targets:
        - httpserver:8000
